# Site settings
title: Dev Blog of Joshua Hamilton
email: 
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my dev blog. This is where I talk about my studies of web development and detail the projects hosted on my GitHub account.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: falconer569
github_username:  falconer569
permalink: /:title.html

# Build settings
markdown: kramdown
